libary(lubridate)
temporal_File <- tempfile()
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip",temporal_File)
hpc <- read.table(unz(temporal_File, "household_power_consumption.txt"), sep = ";", header = T)
unlink(temporal_File)
rm(temporal_File)
hpc$Date <- dmy(hpc$Date)
hpc<- subset(hpc, (hpc$Date == ymd("2007-02-01") | hpc$Date == ymd("2007-02-02")))
hpc$Time <- hms(hpc$Time)
hpc$Global_active_power <- as.numeric(hpc$Global_active_power)
hpc$Global_reactive_power <- as.numeric(hpc$Global_reactive_power)
hpc$Voltage <- as.numeric(hpc$Voltage)
hpc$Global_intensity <- as.numeric(hpc$Global_intensity)
hpc$Sub_metering_1 <- as.numeric(hpc$Sub_metering_1)
hpc$Sub_metering_2 <- as.numeric(hpc$Sub_metering_2)
hpc$Sub_metering_3 <- as.numeric(hpc$Sub_metering_3)
png(filename="plot1.png", width = 480, height = 480)
hist(hpc$Global_active_power, main = "Global Active Power", xlab= "Global Active Power (kilowatts)", ylab = "Frequency", col = "red")
dev.off()
rm(hpc)