libary(lubridate)
temporal_File <- tempfile()
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip",temporal_File)
hpc <- read.table(unz(temporal_File, "household_power_consumption.txt"), sep = ";", header = T)
unlink(temporal_File)
rm(temporal_File)
hpc$Date_Char = hpc$Date
hpc$Date <- dmy(hpc$Date)
hpc<- subset(hpc, (hpc$Date == ymd("2007-02-01") | hpc$Date == ymd("2007-02-02")))
hpc$Date_Time<- hpc$Date + hours(as.numeric(substr(hpc$Time,1,2))) + minutes(as.numeric(substr(hpc$Time,4,5))) + seconds(as.numeric(substr(hpc$Time,7,8)))
png(filename="plot2.png", width = 480, height = 480)
plot(y = hpc$Global_active_power, x = hpc$Date_Time, type = "l", xlab = "", ylab = "Global Active Power (kilowatts)")
dev.off()
rm(hpc)