libary(lubridate)
temporal_File <- tempfile()
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip",temporal_File)
hpc <- read.table(unz(temporal_File, "household_power_consumption.txt"), sep = ";", header = T)
unlink(temporal_File)
rm(temporal_File)
hpc$Date_Char = hpc$Date
hpc$Date <- dmy(hpc$Date)
hpc<- subset(hpc, (hpc$Date == ymd("2007-02-01") | hpc$Date == ymd("2007-02-02")))
hpc$Date_Time<- hpc$Date + hours(as.numeric(substr(hpc$Time,1,2))) + minutes(as.numeric(substr(hpc$Time,4,5))) + seconds(as.numeric(substr(hpc$Time,7,8)))
png(filename="plot3.png", width = 480, height = 480)
plot(y = hpc$Sub_metering_1, x = hpc$Date_Time, type = "l", xlab = "", ylab = "Energy sub metering")
lines(y = hpc$Sub_metering_2, x = hpc$Date_Time, type = "l", col = "red")
lines(y = hpc$Sub_metering_3, x = hpc$Date_Time, type = "l", col = "blue")
legend("topright", legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), col = c("black","red","blue"), lty = c(1,1,1))
dev.off()
rm(hpc)